"""The eight words that open an encrypted wallet QR.

**Eight fixed slots**, so a wrong word count is impossible — the password is generated by the
appliance and is always eight words (`docs/export-password.md`).

**No four-character shortcut, and the number is why.** The EFF large wordlist is *not*
prefix-unique: **5,502 of its 7,776 words are still ambiguous at four characters**, and uniqueness
arrives only at the full word. The seed grid two modules over resolves at four characters because
BIP39 genuinely is unique there. Same widget, different wordlist, different rule — the seam is
`Vocabulary` in `aobs/ui/widgets/wordgrid.py`, and merging the two screens breaks one of them
silently.

**A word not in the list is rejected in its own slot, before anything is decrypted**, which is the
grid's own behaviour and needs nothing here.

**The failure states are distinguished by framing, not by cryptography.** A container whose magic
or version does not parse is a foreign QR and is named as one; a container that parses and whose
tag does not verify says *wrong password or tampering* **without a claim as to which** — the
Poly1305 tag cannot tell them apart, and a verifier that could would hand an offline attacker an
oracle.
"""

from __future__ import annotations

from aobs.core import mnemonic
from aobs.core.constants import EXPORT_PASSWORD_WORDS
from aobs.core.export_password import ExportPassword
from aobs.core.wallet import Network
from aobs.core.wallet_qr import AuthenticationFailed, ForeignContainer, decode
from aobs.ui.wordentry import WordEntryScreen
from aobs.ui.widgets.wordgrid import EFF

TYPE_THEM = (
    "Type the eight words from the paper you kept with this QR. Each word must be typed in full: "
    "unlike your seed words, these are not settled by their first four characters."
)

#: The container holds the BIP39 entropy and the word count, and never the passphrase. A user who
#: does not know that meets a wallet deriving different addresses and no explanation.
NOT_IN_THE_QR = (
    "The passphrase is not in this QR. If your wallet has one, you will be asked for it next and "
    "you must remember it — nothing here can recover it."
)

#: Verbatim, and it claims nothing about which. `AuthenticationFailed` is one condition with two
#: causes and the appliance cannot separate them.
WRONG_PASSWORD = (
    "Wrong password or tampering. The appliance cannot tell which, and will not guess. "
    "Every slot is still editable."
)

#: Reached only if a container gets past the scan screen's own framing check.
NOT_OURS = "This is not an aobs wallet QR."


def wrong_network(backup: Network) -> str:
    """The authenticated check, and the load-bearing one.

    The scan screen already refused this from the cleartext header, so reaching here means the
    cleartext byte disagreed with the byte the tag covers — the tamper path. It refuses in place
    like a wrong password does: a message on the grid, every slot still editable, no wallet loaded
    and no screen transition.

    It names the backup's network and does not offer to switch: the network changes on a path the
    user opens with `F10` and never as a side effect of a scan (`docs/network-selection.md`).
    """
    return (
        f"The words are right, and this backup was exported on {backup.value} — not this "
        f"session's network. Nothing was restored. Choose {backup.value} from the home screen "
        "and scan the code again. Every slot is still editable."
    )


class ExportPasswordScreen(WordEntryScreen):
    def __init__(self, container: bytes) -> None:
        super().__init__("Open your encrypted wallet QR", EFF, EXPORT_PASSWORD_WORDS)
        self._container = container

    def intro(self) -> tuple[str, ...]:
        return (TYPE_THEM, NOT_IN_THE_QR)

    def on_unmount(self) -> None:
        self._container = b""

    def accept(self, words: tuple[str, ...]) -> None:
        try:
            decoded = decode(self._container, ExportPassword(words))
        except ForeignContainer:
            self.grid.say(NOT_OURS)
            return
        except AuthenticationFailed:
            self.grid.say(WRONG_PASSWORD)
            return
        if decoded.network is not self.app.network:  # type: ignore[attr-defined]
            self.grid.say(wrong_network(decoded.network))
            return
        self.app.begin_passphrase(  # type: ignore[attr-defined]
            mnemonic.from_entropy(decoded.entropy)
        )
